SIS/Models/Generals.cs
namespace SIS.Models
{
    public class Generals
    {
        public int Id { get; set; }
        public string? StudentNo { get; set; }
        public string? LessonName { get; set; }
        public double? Midterm { get; set; }
        public double? Final { get; set; }
        public double? Average { get; set; }
        public bool? Pass { get; set; }

    }
}

SIS/Controllers/GeneralController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using SIS.Data;
using SIS.Models;

namespace SIS.Controllers
{
    public class GeneralController : Controller
    {
        public IActionResult PersonalInformation()
        {
            return View();
        }

        // ---------------------------------------
        private readonly SISContext _context;

        public GeneralController(SISContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> GeneralInformation(string searchString)
        {
            if (_context.Students == null)
            {
                return Problem("Entity set 'SISContext.Students'  is null.");
            }
            var students = from s in _context.Students
                           select s;
            if (!String.IsNullOrEmpty(searchString))
            {
                students = students.Where(s => s.FirstName.Contains(searchString)
                                       || s.LastName.Contains(searchString));
            }
            return View(await students.ToListAsync());
        }
        // ---------------------------------------

        public IActionResult ConsultantInfo()
        {
            List<AcademisModel> ConsultantInfo = _context.Academist.ToList();

            return View(ConsultantInfo);
        }


        public IActionResult ExamResult() // Working bro
        {
            List<Generals> examResults = _context.ExamResults.ToList();

            return View(examResults);
        }


        public IActionResult Charts()
        {
            return View();
        }

        public IActionResult ExamSchedule()
        {
            return View();
        }

        public IActionResult IntershipInfo()
        {
            List<StudentInternship> SIntership = _context.StudentInternship.ToList();

            return View(SIntership);
        }

        public IActionResult LessonTaken()
        {
            return View();
        }

        public IActionResult YOKSIS()
        {
            List<OsymInfo> osym = _context.OsymInformations.ToList();

            return View(osym);
        }

        public IActionResult AcademicCalendar()
        {
            return View();
        }

        public IActionResult ExamResultAdd(string? studentNo, string? lessonName)
        {
            // Veritabanından öğrenci numarasına ve ders ismine göre ilgili kaydı bulun
            var examResult = _context.ExamResults.FirstOrDefault(e => e.StudentNo == studentNo && e.LessonName == lessonName);

            if (examResult == null)
            {
                // Belirtilen öğrenci numarası ve ders ismine sahip kayıt bulunamadı
                return NotFound();
            }

            // Modeli oluştur
            var model = new Generals
            {
                StudentNo = examResult.StudentNo,
                LessonName = examResult.LessonName,
                Midterm = examResult.Midterm,
                Final = examResult.Final,
                Average = examResult.Average,
                Pass = examResult.Pass
            };

            return View(model);
        }

        [HttpPost]
        public IActionResult SaveExamResult(Generals model)
        {
            if (ModelState.IsValid)
            {
                // Veritabanında kaydı güncelle
                var examResult = _context.ExamResults.FirstOrDefault(e => e.StudentNo == model.StudentNo && e.LessonName == model.LessonName);

                if (examResult == null)
                {
                    // Belirtilen öğrenci numarası ve ders ismine sahip kayıt bulunamadı
                    return NotFound();
                }

                // Sadece Midterm ve Final alanlarını güncelle
                examResult.Midterm = model.Midterm;
                examResult.Final = model.Final;

                _context.SaveChanges();

                return RedirectToAction("Index", "Home");
            }

            return View(model);
        }


    }

}

SIS/Controllers/StudentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SIS.Data;
using SIS.Models;

namespace SIS.Controllers
{
    public class StudentsController : Controller
    {
        private readonly SISContext _context;

        public StudentsController(SISContext context)
        {
            _context = context;
        }

        // GET: Students
        public async Task<IActionResult> Index(string searchString) 
        {
            if (_context.Students == null)
            {
                return Problem("Entity set 'SISContext.Students'  is null.");
            }
            var students = from s in _context.Students
                           select s;
            if (!String.IsNullOrEmpty(searchString))
            {
                students = students.Where(s => s.FirstName.Contains(searchString)
                                       || s.LastName.Contains(searchString));
            }
            
            return View(await students.ToListAsync());
        }
        

        // GET: Students/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Students == null)
            {
                return NotFound();
            }

            var students = await _context.Students
                .FirstOrDefaultAsync(m => m.Id == id);
            if (students == null)
            {
                return NotFound();
            }

            return View(students);
        }

        // GET: Students/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Students/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,FirstName,LastName,Department,Email,Address,StudentNo,PhoneNumber,BirthDate,RegistrationDate,Gender,IdentificationNumber")] Students students)
        {
            if (ModelState.IsValid)
            {
                _context.Add(students);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(students);
        }

        // GET: Students/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Students == null)
            {
                return NotFound();
            }

            var students = await _context.Students.FindAsync(id);
            if (students == null)
            {
                return NotFound();
            }

            
            return View(students);
        }

        // POST: Students/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FirstName,LastName,Department,Email,Address,StudentNo,PhoneNumber,BirthDate,RegistrationDate,Gender,IdentificationNumber")] Students students)
        {
            if (id != students.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(students);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StudentsExists(students.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            return View(students);
        }

        // GET: Students/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Students == null)
            {
                return NotFound();
            }

            var students = await _context.Students
                .FirstOrDefaultAsync(m => m.Id == id);
            if (students == null)
            {
                return NotFound();
            }


            return View(students);
        }

        // POST: Students/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Students == null)
            {
                return Problem("Entity set 'SISContext.Students'  is null.");
            }
            var students = await _context.Students.FindAsync(id);
            if (students != null)
            {
                _context.Students.Remove(students);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool StudentsExists(int id)
        {
          return (_context.Students?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

SIS/Views/General/Charts.cshtml
@{
    ViewData["Title"] = "Charts Page";
}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>SIS AMASYA</title>
    <link href="https://cdn.jsdelivr.net/npm/simple-datatables@7.1.2/dist/style.min.css" rel="stylesheet" />
    <link href="~/css/styles.css" rel="stylesheet" />
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
</head>
<body class="sb-nav-fixed">
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <!-- Navbar Brand-->
        <a class="navbar-brand ps-3" asp-area="" asp-controller="Home" asp-action="Index">SIS AMASYA</a>
        <!-- Sidebar Toggle-->
        <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
        <!-- Navbar Search-->
        <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
        </form>
        <!-- Navbar-->
        <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                    <li><a class="dropdown-item" href="#!">Settings</a></li>
                    <li><a class="dropdown-item" href="#!">Activity Log</a></li>
                    <li><hr class="dropdown-divider" /></li>
                    <li><a class="dropdown-item" asp-area="" asp-controller="Login" asp-action="Index">Logout</a></li>
                </ul>
            </li>
        </ul>
    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <div class="sb-sidenav-menu-heading">Student Information System</div>
                        <a class="nav-link" asp-area="" asp-controller="General" asp-action="ExamResult">
                            <div class="sb-nav-link-icon"><i class="fas fa-book-open"></i></div>
                            Exam Results
                        </a>
                        <a class="nav-link" asp-area="" asp-controller="Students" asp-action="Index">
                            <div class="sb-nav-link-icon"><i class="fas fa-book-open"></i></div>
                            Students
                        </a>
                        <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                            <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                            General Operations
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>

                        <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav">
                                <a class="nav-link" asp-area="" asp-controller="General" asp-action="PersonalInformation">Personal Information</a>
                                <a class="nav-link" asp-area="" asp-controller="General" asp-action="GeneralInformation">General Information </a>
                                <a class="nav-link" asp-area="" asp-controller="General" asp-action="AcademicCalendar">Academic calendar</a>
                                <a class="nav-link" asp-area="" asp-controller="General" asp-action="ConsultantInfo">Consultant Information</a>
                                <a class="nav-link" asp-area="" asp-controller="General" asp-action="LessonTaken">Lessons Taken</a>
                                <a class="nav-link" asp-area="" asp-controller="General" asp-action="ExamSchedule">Exam Schedule</a>
                                <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Syllabus <!--Mufredat--></a>
                                <a class="nav-link" asp-area="" asp-controller="General" asp-action="IntershipInfo">Internship Information</a>
                                <a class="nav-link" asp-area="" asp-controller="General" asp-action="YOKSIS">YOKSIS Transactions </a>
                            </nav>
                        </div>
                        <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseCourse" aria-expanded="false" aria-controls="collapseCourse">
                            <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                            Course and Term Procedures
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>

                        <div class="collapse" id="collapseCourse" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav">
                                <a class="nav-link" href="#">Drop and Add Courses</a>
                                <a class="nav-link" href="#">Transcript</a>
                            </nav>
                        </div>

                        <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapsePages" aria-expanded="false" aria-controls="collapsePages">
                            <div class="sb-nav-link-icon"><i class="fas fa-book-open"></i></div>
                            Authentication
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse" id="collapsePages" aria-labelledby="headingTwo" data-bs-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav accordion" id="sidenavAccordionPages">
                                <a class="nav-link" asp-area="" asp-controller="Login" asp-action="Index">Login</a>
                                <a class="nav-link" asp-area="" asp-controller="Login" asp-action="Index">Register</a>
                                <a class="nav-link" asp-area="" asp-controller="Login" asp-action="Index">Forgot Password</a>
                            </nav>
                        </div>

                        <div class="sb-sidenav-menu-heading">Addons</div>
                        <a class="nav-link" asp-area="" asp-controller="General" asp-action="Charts">
                            <div class="sb-nav-link-icon"><i class="fas fa-chart-area"></i></div>
                            Charts
                        </a>

                    </div>
                </div>
                <div class="sb-sidenav-footer">
                    <div class="small"></div>
                    SIS AMASYA
                </div>
            </nav>
        </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="~/js/scripts.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
    <script src="~/js/demo/chart-area-demo.js"></script>
    <script src="~/js/demo/chart-bar-demo.js"></script>
    <script src="~/js/demo/chart-pie-demo.js"></script>
</body>
</html>

SIS/Views/General/ConsultantInfo.cshtml
@model List<SIS.Models.AcademisModel>

@{
    ViewData["Title"] = "Constultant Information";
}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>SIS AMASYA</title>
    <link href="https://cdn.jsdelivr.net/npm/simple-datatables@7.1.2/dist/style.min.css" rel="stylesheet" />
    <link href="~/css/styles.css" rel="stylesheet" />
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
</head>
<body class="sb-nav-fixed">
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <!-- Navbar Brand-->
        <a class="navbar-brand ps-3" asp-area="" asp-controller="Home" asp-action="Index">SIS AMASYA</a>
        <!-- Sidebar Toggle-->
        <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
        <!-- Navbar Search-->
        <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
        </form>
        <!-- Navbar-->
        <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                    <li><a class="dropdown-item" href="#!">Settings</a></li>
                    <li><a class="dropdown-item" href="#!">Activity Log</a></li>
                    <li><hr class="dropdown-divider" /></li>
                    <li><a class="dropdown-item" asp-area="" asp-controller="Login" asp-action="Index">Logout</a></li>
                </ul>
            </li>
        </ul>
    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <div class="sb-sidenav-menu-heading">Student Information System</div>
                        <a class="nav-link" asp-area="" asp-controller="General" asp-action="ExamResult">
                            <div class="sb-nav-link-icon"><i class="fas fa-book-open"></i></div>
                            Exam Results
                        </a>
                        <a class="nav-link" asp-area="" asp-controller="Students" asp-action="Index">
                            <div class="sb-nav-link-icon"><i class="fas fa-book-open"></i></div>
                            Students
                        </a>
                        <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                            <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                            General Operations
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>

                        <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav">
                                <a class="nav-link" asp-area="" asp-controller="General" asp-action="PersonalInformation">Personal Information</a>
                                <a class="nav-link" asp-area="" asp-controller="General" asp-action="GeneralInformation">General Information </a>
                                <a class="nav-link" asp-area="" asp-controller="General" asp-action="AcademicCalendar">Academic calendar</a>
                                <a class="nav-link" asp-area="" asp-controller="General" asp-action="ConsultantInfo">Consultant Information</a>
                                <a class="nav-link" asp-area="" asp-controller="General" asp-action="LessonTaken">Lessons Taken</a>
                                <a class="nav-link" asp-area="" asp-controller="General" asp-action="ExamSchedule">Exam Schedule</a>
                                <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Syllabus <!--Mufredat--></a>
                                <a class="nav-link" asp-area="" asp-controller="General" asp-action="IntershipInfo">Internship Information</a>
                                <a class="nav-link" asp-area="" asp-controller="General" asp-action="YOKSIS">YOKSIS Transactions </a>
                            </nav>
                        </div>
                        <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseCourse" aria-expanded="false" aria-controls="collapseCourse">
                            <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                            Course and Term Procedures
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>

                        <div class="collapse" id="collapseCourse" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav">
                                <a class="nav-link" href="#">Drop and Add Courses</a>
                                <a class="nav-link" href="#">Transcript</a>
                            </nav>
                        </div>

                        <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapsePages" aria-expanded="false" aria-controls="collapsePages">
                            <div class="sb-nav-link-icon"><i class="fas fa-book-open"></i></div>
                            Authentication
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse" id="collapsePages" aria-labelledby="headingTwo" data-bs-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav accordion" id="sidenavAccordionPages">
                                <a class="nav-link" asp-area="" asp-controller="Login" asp-action="Index">Login</a>
                                <a class="nav-link" asp-area="" asp-controller="Login" asp-action="Index">Register</a>
                                <a class="nav-link" asp-area="" asp-controller="Login" asp-action="Index">Forgot Password</a>
                            </nav>
                        </div>

                        <div class="sb-sidenav-menu-heading">Addons</div>
                        <a class="nav-link" asp-area="" asp-controller="General" asp-action="Charts">
                            <div class="sb-nav-link-icon"><i class="fas fa-chart-area"></i></div>
                            Charts
                        </a>

                    </div>
                </div>
                <div class="sb-sidenav-footer">
                    <div class="small"></div>
                    SIS AMASYA
                </div>
            </nav>
        </div>

        <div id="layoutSidenav_content">
            <div class="container-fluid px-4">
                <main>
                    <div class="container-fluid px-4">
                        <h1 class="mt-4">CONSULTANT INFORMATION</h1>
                        <ol class="breadcrumb mb-4">
                            <li class="breadcrumb-item active">Constultant Information</li>
                        </ol>

                        <div class="card mb-4">
                            <div class="card-header">
                                <i class="fas fa-table me-1"></i>
                                Constultant DataTable
                            </div>
                            <div class="card-body">
                                <table id="datatablesSimple">
                                    <thead>
                                        <tr>
                                            <th>Id</th>
                                            <th>Lesson Advisor First Name</th>
                                            <th>Lesson Advisor Last Name</th>
                                            <th>Lesson Advisor Full Name</th>
                                            <th>Department</th>
                                            <th>Lesson Name</th>
                                            <th>Lesson Code</th>
                                            <th>Title</th>
                                            <th>Email</th>
                                            <th>Phone</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var academist in Model.Take(6))
                                        {
                                            <tr>
                                                <td>@academist.Id</td>
                                                <td>@academist.LessonAdvisorFN</td>
                                                <td>@academist.LessonAdvisorLN</td>
                                                <td>@academist.LessonAdvisorFullName</td>
                                                <td>@academist.Department</td>
                                                <td>@academist.LessonName</td>
                                                <td>@academist.LessonCode</td>
                                                <td>@academist.Title</td>
                                                <td>@academist.Email</td>
                                                <td>@academist.Phone</td>
                                            </tr>
                                        }
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </main>
                @*<div class="card">
                    <div class="card-body">
                        <table id="datatablesSimple">
                            <thead>
                                <tr>
                                    <th>Id</th>
                                    <th>Lesson Advisor First Name</th>
                                    <th>Lesson Advisor Last Name</th>
                                    <th>Lesson Advisor Full Name</th>
                                    <th>Department</th>
                                    <th>Lesson Name</th>
                                    <th>Lesson Code</th>
                                    <th>Title</th>
                                    <th>Email</th>
                                    <th>Phone</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var academist in Model.Take(6))
                                {
                                    <tr>
                                        <td>@academist.Id</td>
                                        <td>@academist.LessonAdvisorFN</td>
                                        <td>@academist.LessonAdvisorLN</td>
                                        <td>@academist.LessonAdvisorFullName</td>
                                        <td>@academist.Department</td>
                                        <td>@academist.LessonName</td>
                                        <td>@academist.LessonCode</td>
                                        <td>@academist.Title</td>
                                        <td>@academist.Email</td>
                                        <td>@academist.Phone</td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                     </div>
                </div>*@
            </div>

        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="~/js/scripts.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
    <script src="~/js/demo/chart-area-demo.js"></script>
    <script src="~/js/demo/chart-bar-demo.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/simple-datatables@7.1.2/dist/umd/simple-datatables.min.js" crossorigin="anonymous"></script>
    <script src="~/js/datatables-simple-demo.js"></script>
</body>
</html>